version: "2"
services:
    www:
        build: .
        volumes:
            - ./www:/var/www/html/
        ports:
            - 8080:80
        links:
            - db
        networks:
            - default
        depends_on:
            - db
    db:
        build: ./database
        ports: 
            - "3306:3306"
        environment:
            MYSQL_DATABASE: mydb
            MYSQL_USER: user
            MYSQL_PASSWORD: user
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - persistent:/var/lib/mysql
        networks:
            - default
    phpmyadmin:
        image: vulhub/phpmyadmin:4.8.1
        volumes:
            - ./www/config.inc.php:/var/www/html/config.inc.php
        depends_on:
            - db
        links:
            - db
        ports:
            - 8001:80
        environment:
            MYSQL_DATABASE: mydb
            MYSQL_USER: user
            MYSQL_PASSWORD: user
            MYSQL_ROOT_PASSWORD: root  
volumes:
    persistent: 
