version: "2"
services:
    www:
        build: .
        volumes:
            - ./www:/var/www/html/
        ports:
            - 8080:80
        links:
            - db
        networks:
            - default
        depends_on:
            - db
    db:
        image: mysql:5.7
        restart: always
        ports: 
            - "3307:3306"
        environment:
            MYSQL_DATABASE: mydb
            MYSQL_USER: user
            MYSQL_PASSWORD: user
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - persistent:/var/lib/mysql
            - ./database/mydb.sql:/docker-entrypoint-initdb.d/mydb.sql
        networks:
            - default
volumes:
    persistent: 
